# Generated by Django 5.0.2 on 2026-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0019_customer_and_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
